export const cities = {
  europe: [
    {
      image: "/cities/paris.jpg",
      city: "Paris",
      country: "France",
      flag: "/flags/france.jpg",
    },
    {
      image: "/cities/london.jpg",
      city: "London",
      country: "United Kingdom",
      flag: "/flags/united-kingdom.png",
    },
    {
      image: "/cities/instanbul.jpg",
      city: "Istanbul",
      country: "Turkey",
      flag: "/flags/turkey.png",
    },
    {
      image: "/cities/rome.jpg",
      city: "Rome",
      country: "Italy",
      flag: "/flags/italy.png",
    },
    {
      image: "/cities/barcelona.jpg",
      city: "Barcelona",
      country: "Spain",
      flag: "/flags/spain.png",
    },
    {
      image: "/cities/amsterdam.jpg",
      city: "Amsterdam",
      country: "Netherlands",
      flag: "/flags/netherlands.png",
    },
    {
      image: "/cities/vienna.jpg",
      city: "Vienna",
      country: "Austria",
      flag: "/flags/austria.png",
    },
    {
      image: "/cities/prague.jpg",
      city: "Prague",
      country: "Czech Republic",
      flag: "/flags/czech-republic.png",
    },
    {
      image: "/cities/munich.jpg",
      city: "Munich",
      country: "Germany",
      flag: "/flags/germany.png",
    },
    {
      image: "/cities/budapest.jpg",
      city: "Budapest",
      country: "Hungary",
      flag: "/flags/hungary.png",
    },
  ],
  northAmerica: [
    {
      image: "/cities/new-york.jpg",
      city: "New York",
      country: "United States",
      flag: "/flags/united-states.png",
    },
    {
      image: "/cities/las-vegas.jpg",
      city: "Las Vegas",
      country: "United States",
      flag: "/flags/united-states.png",
    },
    {
      image: "/cities/san-francisco.jpg",
      city: "San Francisco",
      country: "United States",
      flag: "/flags/united-states.png",
    },
    {
      image: "/cities/los-angeles.jpg",
      city: "Los Angeles",
      country: "United States",
      flag: "/flags/united-states.png",
    },
    {
      image: "/cities/cancun.jpg",
      city: "Cancun",
      country: "Mexico",
      flag: "/flags/mexico.png",
    },
  ],
  asia: [
    {
      image: "/cities/bangkok.jpg",
      city: "Bangkok",
      country: "Thailand",
      flag: "/flags/thailand.png",
    },
    {
      image: "/cities/singapore.jpg",
      city: "Singapore",
      country: "Singapore",
      flag: "/flags/singapore.png",
    },
    {
      image: "/cities/tokyo.jpg",
      city: "Tokyo",
      country: "Japan",
      flag: "/flags/japan.png",
    },
    {
      image: "/cities/seoul.jpg",
      city: "Seoul",
      country: "South Korea",
      flag: "/flags/south-korea.png",
    },
    {
      image: "/cities/hong-kong.jpg",
      city: "Hong Kong",
      country: "China",
      flag: "/flags/china.png",
    },
  ],
  africa: [
    {
      image: "/cities/cape-town.jpg",
      city: "Cape Town",
      country: "South Africa",
      flag: "/flags/south-africa.png",
    },
    {
      image: "/cities/marrakech.jpg",
      city: "Marrakech",
      country: "Morocco",
      flag: "/flags/morocco.png",
    },
    {
      image: "/cities/johannesburg.jpg",
      city: "Johannesburg",
      country: "South Africa",
      flag: "/flags/south-africa.png",
    },
    {
      image: "/cities/sharm-el-sheikh.jpg",
      city: "Sharm El-Sheikh",
      country: "Egypt",
      flag: "/flags/egypt.png",
    },
    {
      image: "/cities/durban.jpg",
      city: "Durban",
      country: "South Africa",
      flag: "/flags/south-africa.png",
    },
  ],
  oceania: [
    {
      image: "/cities/sydney.jpg",
      city: "Sydney",
      country: "Australia",
      flag: "/flags/australia.png",
    },
    {
      image: "/cities/melbourne.jpg",
      city: "Melbourne",
      country: "Australia",
      flag: "/flags/australia.png",
    },
    {
      image: "/cities/brisbane.jpg",
      city: "Brisbane",
      country: "Australia",
      flag: "/flags/australia.png",
    },
    {
      image: "/cities/perth.jpg",
      city: "Perth",
      country: "Australia",
      flag: "/flags/australia.png",
    },
    {
      image: "/cities/auckland.jpg",
      city: "Auckland",
      country: "New Zealand",
      flag: "/flags/new-zealand.png",
    },
  ],
  southAmerica: [
    {
      image: "/cities/rio-de-janeiro.jpg",
      city: "Rio de Janeiro",
      country: "Brazil",
      flag: "/flags/brazil.png",
    },
    {
      image: "/cities/sao-paulo.jpg",
      city: "São Paulo",
      country: "Brazil",
      flag: "/flags/brazil.png",
    },
    {
      image: "/cities/buenos-aires.jpg",
      city: "Buenos Aires",
      country: "Argentina",
      flag: "/flags/argentina.png",
    },
    {
      image: "/cities/cusco.jpg",
      city: "Cusco",
      country: "Peru",
      flag: "/flags/peru.png",
    },
    {
      image: "/cities/lima.jpg",
      city: "Lima",
      country: "Peru",
      flag: "/flags/peru.png",
    },
  ],
};
